##############
# Application Custom Values
#############
stage_allowed_destinations: &stage_allowed_destinations
  - namespace: labs-staging
    server: https://kubernetes.default.svc
helm_repository: &helm_repo "http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/helm-charts/"
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
    - group: integreatly.org
      kind: GrafanaDataSource
      jsonPointers:
        - /spec/datasources/0/secureJsonData/httpHeaderValue1
##############
# Argo App of Apps declaration
#############
argocd_projects:
  - enabled: true
    name: pet-battle-stage
    destinations: *stage_allowed_destinations
    cluster_resource_white_list:
      - group: 'rbac.authorization.k8s.io'
        kind: 'ClusterRole'
      - group: 'rbac.authorization.k8s.io'
        kind: 'ClusterRoleBinding'
applications:
  pet_battle_api_stage:
    name: pet-battle-api-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-api
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.15
    values:
      fullnameOverride: pet-battle-api
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-api
      image_version: "1.0.1"
      istag:
        enabled: false
      deploymentConfig: false
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-stage
      enabled: true
  pet_battle_stage:
    name: pet-battle-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.6
    values:
      fullnameOverride: pet-battle
      image_repository: quay.io
      image_name: pet-battle
      image_namespace: petbattle
      config_map: '{ "catsUrl": "https://pet-battle-api-labs-staging.apps.hivec.sandbox309.opentlc.com", "tournamentsUrl": "https://pet-battle-tournament-labs-staging.apps.hivec.sandbox309.opentlc.com", "matomoUrl": "https://matomo-labs-ci-cd.apps.hivec.sandbox309.opentlc.com/", "keycloak": { "url": "https://keycloak-labs-staging.apps.hivec.sandbox309.opentlc.com/auth/", "realm": "pbrealm", "clientId": "pbclient", "redirectUri": "https://pet-battle-labs-staging.apps.hivec.sandbox309.opentlc.com/*", "enableLogging": true } }'
      image_version: "1.3.1"
    project:
      name: pet-battle-stage
      enabled: true
  pet_battle_tournament_stage:
    name: pet-battle-tournament-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-tournament
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.39
    values:
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-tournament
      image_namespace: labs-staging
      image_version: "1.0.1"
      istag:
        enabled: false
      pet-battle-infra:
        app_domain: apps.hivec.sandbox309.opentlc.com
        ignoreHelmHooks: true
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-stage
      enabled: true
  _stage:
    source_ref: "null"
    values:
      image_version: "null"
      image_namespace: petbattle
      image_repository: quay.io
