apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-tagging-pipeline
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-m2
    - name: git-auth-secret
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_REPO_URL
    type: string
    description: Git cicd repo url
    default: "https://github.com/tersian/ubiquitous-journey.git"
  - name: GIT_BRANCH
    description: The Git Branch (branch,tag,revision) to set for the app
    type: string
    default: "master"
  - name: ARGOCD_CONFIG_REPO_PATH
    description: The App Values file
    type: string
    default: ""
  - name: APP_OF_APPS_KEY
    type: string
    default: ""
  tasks:
    - name: fetch-cicd-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_REPO_URL)"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)/cicd"
        - name: deleteExisting
          value: "true"

    - name: git-commit
      retries: 1
      taskRef:
        name: git-commit-argo-versions-mvn
      workspaces:
        - name: git-auth-secret
          workspace: git-auth-secret
        - name: maven-settings
          workspace: maven-settings
        - name: maven-m2
          workspace: maven-m2
        - name: output
          workspace: shared-workspace
      params:
      - name: APPLICATION_NAME
        value: "$(params.APPLICATION_NAME)"
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)/cicd"
      - name: WORK_DIRECTORY_APP
        value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
      - name: GIT_TAG
        value: "$(params.GIT_BRANCH)"
      - name: APP_OF_APPS_KEY
        value: "$(params.APP_OF_APPS_KEY)"
      - name: ARGOCD_CONFIG_REPO_PATH
        value: "applications/deployment/values-applications-test.yaml"
      runAfter:
      - fetch-cicd-repository
